algoritmo "semnome"
// Função: Calcula consumo médio baseado na distância percorrida e combustível gasto.
// O que faz: Recebe distância e combustível, divide distância pelo combustível e mostra consumo médio.
// Autor :
// Data : 23/09/2025
// Seção de Declarações 
var
km, L: inteiro
inicio
escreval ("Distancia: ")
leia (km)
escreval ("Litros: ")
leia (L)
escreval (" a media é:", km/L )

fimalgoritmo

