algoritmo "semnome"
// Função: Calcula valor em reais a partir do valor em dólar e cotação.
// O que faz: Lê cotação do dólar e quantidade em dólares, calcula e exibe valor em reais.
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
qt, c, reais: real
inicio
escreval ("Digite quantos dolares você tem:")
leia(qt)
escreval ("Digite a cotacao de dolar de hoje:")
leia(c)
reais <- qt * c
escreval ("você tem: R$ -", reais)










fimalgoritmo

