algoritmo "semnome"
// Função :
// Autor :
// Data : 23/09/2025
// Seção de Declarações 
var
N:caractere
P1:real
P2:real
P3:real
inicio
escreva("Nome do aluno(a): ")
leia (N)
escreva ("Prova1: ")
leia (P1)
escreva ("Prova2: ")
leia (P2)
escreva ("Prova3: ")
leia (P3)
escreval (" a soma é: ", P1 + P2 + P3)
escreval (" a sua média é: ",(P1 + P2 + P3)/3)
// Seção de Comandos 
fimalgoritmo
