algoritmo "semnome"
// Função: Divide valor da compra em 5 prestações iguais.
// O que faz: Lê valor da compra, calcula parcela dividindo por 5 e exibe valor das parcelas.
// Autor :
// Data : 30/09/2025
// Seção de Declarações
var
vc, vp: Real
inicio
Escreva("Digite o valor total da compra: R$ ")
Leia(vc)
vp <- vc /5
Escreva("O valor de cada prestação é: R$ ", vp:0:2)
// Seção de Comandos
fimalgoritmo

