algoritmo "semnome"
// Função :
// Autor :
// Data : 23/09/2025
// Seção de Declarações 
var
n: CARACTERE
S: real
c: real
inicio
escreva ("Nome do funcionario:")
leia(n)
escreva ("Salario do mês: ")
leia (s)
escreva ("Numero de comissão: ")
leia (c)
escreval ("15% da comissão é: ", c * 0.15)
escreval ("salário com a comissão é: ", s + c * 0.15 )
// Seção de Comandos 
fimalgoritmo
