algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações
var
n1, n2: inteiro
inicio
escreva("Digite o primeiro número: ")
leia(n1)

escreva("Digite o segundo numero: ")
leia (n2)

se n1 = n2 entao
   escreva ("Os numeros são iguais")
   senao
   se n1 > n2 entao
      escreva ("O maior número é:", n1)
      senao
      escreva("O maior numero é: ",n2)
   Fimse
FIMSE
// Seção de Comandos
FIMALGORITMO
