algoritmo "semnome"
// Função: Converte uma temperatura em Celsius para Fahrenheit.
// O que faz: Lê temperatura em Celsius, aplica fórmula e exibe a temperatura convertida.
// Autor :
// Data : 25/09/2025
// Seção de Declarações 
var
F: Real
C: Real

inicio
escreval ("Temperatura em celcius: ")
leia(c)
F<-(9*C+160) / 5
escreval (C, " em celsius é o mesmo que , " , F , " em Fahrenheit")
// Seção de Comandos 
fimalgoritmo

