algoritmo "atividade"
// Função: Recebe dois números e exibe a soma.
// O que faz: Lê dois valores, calcula a soma e imprime o resultado.
// Autor : Vitor Siqueira
// Data : 23/09/2025
// Seção de Declarações
var
numero1, numero2: inteiro

inicio
//

escreva("digite numero1")
leia (numero1)
escreva ("digite numero2")
leia (numero2)
escreva("a soma é:", numero1 + numero2)
// Seção de Comandos
fimalgoritmo


