algoritmo "semnome"
// Função :
// Autor :
// Data : 06/10/2025
// Seção de Declarações 
var
i, idade: inteiro
inicio
para i de 1 ate 7 faca
   escreva ("informe a idade da pessoa", i,": ")
  leia (idade)
   
   se idade>= 18 entao
   escreval("Pessoa", i," é MAIOR de idade.")
   senao
   escreval ("Pessoa", i,"é MENOR de idade.")
   fimse
   
   escreval("")
   fimpara







// Seção de Comandos 
fimalgoritmo
