algoritmo "semnome"
// Função: Exibe mensagem se número >80, <25 ou =40.
// O que faz: Lê número e exibe mensagem de acordo com valor.
// Autor :
// Data : 13/10/2025
// Seção de Declarações 
Var
    numero: inteiro
Inicio
    Escreva("Digite um número: ")
    Leia(numero)

    Se (numero > 80) ou (numero < 25) ou (numero = 40) Entao
        Escreva ("o numero esta dentro das condições")
    FimSe
Fimalgoritmo
// Seção de Comandos 
fimalgoritmo

